### ISSUE TITLE
Add Configurable item DisplayBook to narrow down the where the app looks for books

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#162]
Under the Portal URL: "" in the configuration JS add the configurable item DISPLAY BOOKS

//Choose which books will be displayed in your application
//To search only your ArcGIS Online organization of Portal for ArcGIS site for briefing books use the "organization" parameter. This will prevent you from see other organizations briefing books
//To search all of ArcGIS.com for briefing books use the "all" parameter. You may see books that don't belong to you when you choose this option.
//To search only a group for briefing books use the "group" parameter. This option is great for organizations that are sharing briefing books between organizations.

DisplayBook: "organization"  \\organization, all, group

//If you have selected "group" in the above parameter then add the group ID you would like to search
DisplayGroup: ""  // Add your group ID something like ""ADK45JUG930303"

organization = Only Search My Organizations Briefing Book items. (This will limit searching to only the organization defined)
all = Search All of ArcGIS.com for Briefing Books items
group=Search only the "Defined Group" for Briefing Book items

@conklinbd @ScottOppmann We've talked about this change a few times. Just do a quick review and let me know if this still works. 

This should increase stability and performance in the application. Giving users more control over there book and app content.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We have a question. When ‘DisplayBook’ is set to ‘group’ and user creates a new book then, by default the book is private and not shared with the configured group. Hence when user reloads the application, the new book will not be shown in the gallery. Is this OK or should we share the book to the configured group by default?

**Comment by LindsayThomas** [comment]
LT Note: 
Tested the following 
A. If “anonymous access” is enabled  (user is  not prompted for PW)
B. If “anonymous access” is disabled (user is prompted for PW)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam 
Have you tested the following scenario:
Briefing Books created from the same application (DisplayBook: all, and PortalURL: http://arcgis.com.) 
on two different AGOL accounts? 

I would expect that the user would be able to see any of the books created on the application with this configuration. However, I am not see that in all scenarios. I've been trying to isolate but I haven't had a lot of luck. 
Are you seeing this issue as well?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas, we were able to see books created using two different accounts. We only needed to ensure that the books were shared to `everyone`, otherwise it would be only visible to the owner after logging in.

**Comment by LindsayThomas** [comment]
If you go to http://50.112.45.253/briefingbookauthor/default.htm (you will see 5 books that are shared with everyone. The books are coming from several different organizations. 

If you use the new application code from develop_2.0 (with all, the URL pointing to http://arcgis.com and with the tag "solutionstryitliveview" then you will not see all the books

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
If you use develop_2.0, then you will not see all the books because:
1. The books seem to be created using a version of the app below v1.1
2. We added the typekeywords "JavaScript" and "Configurable" while creating a book in v1.1. This was a contribution from Mike Tschudi to fix issue #118.
3. In develop_2.0 we changed the query to search books to include the typekeywords to return items only of above types to increase performance by narrowing the search results. `‘typekeywords:JavaScript AND type:Web Mapping Application’  `
4. Due this changed query, all the five books are not visible now while using develop_2.0 because they do not have those typekeywords

To view these books in develop_2.0, we see two following options:
1. Add the typekeywords manually by logging into Org to these items OR
2. Modify the app temporarily to remove the typekeyword from the search query, this will display all books. Open each book and save them. While saving, the app will add the typekeywords to those books. The books will now be visible in develop_2.0.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Let's discuss today

**Comment by LindsayThomas** [comment]
LT - June Version builds books Web Mapping Application (Ready to Use, Other)
April Version builds books Web Mapping Application (JavaScript, Configurable)
Develop 2.0 works with April Version.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam This approach is okay.No further action is required.
