### ISSUE TITLE
Editing on different screen resolutions will create different book dimensions. 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#169]
Repro Steps

-Add an image in full screen size edit mode. Enusre the image is set at the desired size
-Now make the browser half the size.  
-Note what happens to the image (it is smaller)
-Make the screen full size again 
-The images do not return to their original sizes

The images stay at the reduced size after you exit “Edit” mode, regardless of whether or not you save the Briefing Book or whether or not you are in “Edit” mode to begin with

So, Briefing Book will appear differently on different devices based on the size of the screen you create edits. 

Note for LT- from DL

**Comment by LindsayThomas** [comment]
@WKnol We don't have release date yet. We are targeting 2015 but I can't narrow it down to the month yet since we are still in development.

**Comment by WKnol** [comment]
thanks for the reply, I will follow the development to see when it will be released.

Van: Lindsay Thomas [mailto:notifications@github.com]
Verzonden: maandag 5 januari 2015 22:28
Aan: Esri/briefing-book
CC: Knol, Wilfred
Onderwerp: Re: [briefing-book] Editing on different screen resolutions will create different book dimensions. (#169)


@WKnol<https://github.com/WKnol> We don't have release date yet. We are targeting 2015 but I can't narrow it down to the month yet since we are still in development.

**Comment by WKnol** [comment]
thanks for the reply, I will folow the development to see when it will be released.

**Comment by LindsayThomas** [comment]
Verified that images get small but then return to original size as the browser is made bigger and smaller.
