### ISSUE TITLE
Some tags causes load failure for all books in the application gallery

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#171]
Some tags causes load failure for all books in the application gallery
Some "tags" cause the Briefing book application books to fail. 

DNR, Fire are both tags that fail. Support has reported this issue. I need to add the NIM

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam  If you test the briefing book with the following settings
       DisplayBook: "all"
       ConfigSearchTag: "Fire",  (or set to DNR)
Will the Gallery Load?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas  We tested the app with the provided configuration setting and found that the app gallery doesn't load. This is because one of the searched result items belongs to an expired organization, app fails to access that item.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Can we ignore the failure of that item loading and allow all items that are accessible to be added to the gallery?

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Per phone discussion and fix from Mike Miller. Please let us know if the workaround provided by Mike will work.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Please provide the user experience and workflows for the implemented fix as discussed on the call this week.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
Here is how the user experience will be

User has not signed in:

1. App loads and encounters a book from an expired Org
2. App displays item-sign-in dialog (this is not app sign-in)
3. Since Org is expired, user cannot log in or even if he logs in with Org credentials, he wont have access to the book, since the Org has expired
4. We are not entirely sure about what message is displayed in item-sign-in dialog, since we do not have access to an Org that has expired. 
5. If user signs in with proper credentials of a different Org that is active, then the item-sign-in is successful, but user still does not have access to book from expired Org. The app will skip such books belonging to expired Orgs and users will not see any message.
6. If user cancels the item-sign-in dialog, app will skip such books belonging to expired Orgs. Users will not see any message.

User has signed in:

1. When the app spins up it will automatically display the item-sign-dialog
2. User can click cancel or provide credentials to item-sign-in dialog
3. App will skip books belonging to expired Orgs. Users do not see any message.
4. User clicks "Sign-in" icon to sign in to the app and provides proper credentials
5. If Org allows searching public items outside the Org then the app fetches all books again. This time, it again encounters books from expired Orgs and displays the item-sign-in-dialog.
    6. If users click "Cancel" in this item-sign-in dialog, the app will skip such books without displaying any message to users.
7. If Org does not allow searching public items outside the Org, then the app will never hit expired books, since the books are searched only within the Org.

Some additional notes about apps configured with OAuthID:

1. When app spins up, it will redirect to AGOL login page
2. If user "Approves" or enters credentials, the app will skip expired books and load others normally
3. If user clicks "No thanks" or clicks cancel on AGOL sign in page, then AGOL redirects the browser to load the app again. This triggers a reload of the app and the AGOL sign-in page is displayed again. Users will never be able to get into the app without signing in. We cannot prevent this as this is how apps using OAuth behave, i.e. after successful sign-in the app is reloaded.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam 
Can we automatically ignore all Expired items? (It seems the application knows they are expired before being challenged. So, can we just dismiss this and ignore by default?)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
The JS API automatically invokes identity manager when it touches an expired book. We do not have control over not displaying the identity manager.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Please implement.

**Comment by LindsayThomas** [comment]
Verified. 
Works with 'all' and 'org'
