### ISSUE TITLE
The sample briefing book does not work in Internet Explorer 9 (IE9)

### ISSUE THREAD

**Issue by aOrtego** [Esri/briefing-book#187]
1. Open Internet Explorer and open the console (F12). If using a version later than 9, change the document mode to Internet Explorer 9 compatibility.
2. Visit the following site, an example of the Briefing Book application from Esri's GitHub Page:
http://50.112.45.253/briefingbook/default.htm
3. Test this link in a later version of Internet Explorer, or Chrome or Firefox, to verify that it is accessible to you.
4. Open the link in IE9 (or a compatibility version of IE9) and note that four RequestErrors appear, making the content inaccessible.

**Comment by LindsayThomas** [comment]
@aOrtego Has this been tested on a secured application? Per the requirements IE9 is only supported if the application is setup that way?

**Comment by aOrtego** [comment]
This issue is regarding Esri's sample application, so I don't know how it is being hosted.

**Comment by conklinbd** [comment]
@aOrtego The customer will need to deploy this app to their own web server, secured with SSL, using a trusted certificate authority. The sample app is not intended for their production use and we do not currently have it SSL enabled.

**Comment by LindsayThomas** [comment]
@aOrtego @conklinbd    Andrew and I had a few off thread conversation on this issue. The issue above is related to only viewing the application in IE9 not the authoring/viewing. We need to support either support viewing of the application in IE9, or update the documentation to reflect the app isn't supported for viewing only unless the app is secured with SSL (like we say for authoring). 

@conklinbd I think this could be a bounce back.

I am closing this issue. A new issue will be opened related to this once it comes through Esri Support via triage, and we decide whether the fix is documentation OR app related.
