### ISSUE TITLE
Print button not available when user is now logged in

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#198]
If a book is private then the print option is not available to the user. 

Repro Steps
1. Login 
2. Click on book to print
3. Print button is not available to print

@CTLocalGovTeam

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Per our discussion this week. 
Please provide the ability for the user to print when she has signed in with her credentials. 

I realized that in the issue, we said only implement print in "view only" mode. However, the we both had a different understand of view only mode. 

To be clear. We do  not need to have print functionality when the user is in "edit mode" (edit mode in this case is defined as having the edit screen expanded.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas Ok. We will provide print functionality after user signs in. The placement of 'Print' icon is highlighted with red in below mockup. This icon will not be available when book is expanded for editing by clicking 'Edit Book' icon.

![image](https://cloud.githubusercontent.com/assets/2959186/6863970/d4b4ee88-d480-11e4-840d-01654c8a8cf8.png)


Please confirm.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Is the print icon going to be disabled (muted and unselectable) or is the intention that as you open and close an edit session the button will disappear? 

When the user sets the authormode = false then where will the print button show in the UI for users that have signed in?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas The print icon will disappear when user starts editing a book because the number of icons shown in the header are too many. It will be displayed again when user closes the editing session for a book as shown in the above screenshot. Below is the screenshot when the book is being edited.

![image](https://cloud.githubusercontent.com/assets/2959186/6891604/814d8bfe-d6da-11e4-934f-936af369767f.png)

When user sets `AuthoringMode: false` then print button will be shown as depicted in the below screenshot.

![image](https://cloud.githubusercontent.com/assets/2959186/6891923/74edc26e-d6dc-11e4-8e19-948dbd39859a.png)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Is there a reason why we are putting the print button between the save button and Contents button (user logged in mode) vs. next to the home button when the user is logged out? 

Can we make it consistent? So, print button is located next to the home button in both cases?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas  We will place the print button next to the home button.

**Comment by LindsayThomas** [comment]
print icon exists in public and private view (button in same location too)
test public private
